"use client";
import Image from "next/image"; import Link from "next/link"; import { useEffect, useMemo, useState } from "react";
import { business } from "../data/business"; import { categories, products, type Product } from "../data/menu";
import { reviews, reviewsSummary } from "../data/reviews";
type Cart = Record<string,number>;
const money=(n:number)=>new Intl.NumberFormat("ru-RU").format(n)+" ₽";
const fallback="/images/demo-food-fallback.svg";
function HeroVisual(){return <div className="hero-visual" aria-label="Блюда из меню Ешь!ка"><div className="hero-photo hero-photo-main"><Image src="/images/menu/hotdog-danish.jpg" fill priority sizes="(max-width:760px) 68vw, 28vw" alt="Хот-дог Датский"/></div><div className="hero-photo hero-photo-shawarma"><Image src="/images/menu/shawarma-classic.jpg" fill sizes="(max-width:760px) 38vw, 16vw" alt="Шаурма классическая"/></div><div className="hero-photo hero-photo-roll"><Image src="/images/menu/caesar-roll.jpg" fill sizes="(max-width:760px) 35vw, 15vw" alt="Цезарь ролл"/></div><div className="hero-photo hero-photo-snack"><Image src="/images/menu/nuggets.jpg" fill sizes="(max-width:760px) 27vw, 11vw" alt="Наггетсы"/></div></div>}
const excerpt=(text:string)=>text.length>220?`${text.slice(0,220).trimEnd()}…`:text;
function ReviewsSection(){return <section className="reviews" aria-labelledby="reviews-title"><div className="reviews-head"><div><p className="eyebrow">Отзывы</p><h2 id="reviews-title">Что говорят гости</h2><p>Отзывы посетителей Ешь!ка на Яндекс Картах</p></div><div className="reviews-score"><strong>★ {reviewsSummary.rating.toFixed(1)}</strong><span>Рейтинг на Яндекс Картах · {reviewsSummary.ratingCount} оценки</span><a href={reviewsSummary.reviewsUrl} target="_blank" rel="noopener noreferrer">Все отзывы ↗</a></div></div><div className="reviews-track">{reviews.map(review=><article className="review-card" key={review.id}><div className="review-stars" aria-label={`${review.rating} из 5`}>{"★".repeat(review.rating)}</div><p>«{excerpt(review.text)}»</p><footer><span className="review-avatar" aria-hidden="true">{review.authorName[0]}</span><span><b>{review.authorName}</b><small>{review.date&&`${review.date} · `}Яндекс Карты</small></span></footer></article>)}</div></section>}
export function CafeApp(){ const [cart,setCart]=useState<Cart>({}); const [drawer,setDrawer]=useState(false); const [active,setActive]=useState(categories[0].id);
 useEffect(()=>{ const stored=localStorage.getItem("eshka-cart"); if(stored) setCart(JSON.parse(stored)); },[]); useEffect(()=>localStorage.setItem("eshka-cart",JSON.stringify(cart)),[cart]); useEffect(()=>{const esc=(e:KeyboardEvent)=>e.key==="Escape"&&setDrawer(false); window.addEventListener("keydown",esc); return()=>window.removeEventListener("keydown",esc)},[]);
 const cartProducts=products.filter(p=>cart[p.id]); const count=Object.values(cart).reduce((a,b)=>a+b,0); const total=cartProducts.reduce((s,p)=>s+p.price*cart[p.id],0); const shown=useMemo(()=>products.filter(p=>p.categoryId===active),[active]); const change=(id:string, amount:number)=>setCart(c=>{const n=(c[id]||0)+amount; const next={...c}; if(n<=0) delete next[id]; else next[id]=n; return next});
 const choose=(id:string)=>{setActive(id); document.getElementById("menu")?.scrollIntoView({behavior:"smooth",block:"start"});};
 return <><header><a className="logo" href="#top" aria-label="Ешь!ка — на главную">Ешь<span>!</span>ка</a><nav><a href="#menu">Меню</a><a href="#about">О кафе</a><a href="#contacts">Контакты</a></nav><a className="phone" href={`tel:${business.phoneHref}`}>{business.phone}</a><button className="cart-button" onClick={()=>setDrawer(true)} aria-label="Открыть корзину">Корзина <b>{count}</b></button></header>
 <main id="top"><section className="hero"><div><p className="eyebrow">Кафе быстрого питания · Таганрог</p><h1>Еда, когда хочется быстро и по делу.</h1><p className="lead">Выберите блюда из меню и оформите заказ на самовывоз или доставку.</p><div className="actions"><a className="primary" href="#menu">Выбрать еду</a><a className="secondary" href="#contacts">Как нас найти</a></div></div><HeroVisual/></section>
 <section id="menu" className="menu"><div className="menu-title"><p className="eyebrow">Меню</p><h2>Выберите, что съесть сейчас</h2><p>Актуальные позиции и цены из меню кафе.</p></div><div className="categories" role="tablist" aria-label="Категории меню">{categories.map(c=><button key={c.id} className={active===c.id?"active":""} onClick={()=>choose(c.id)} role="tab" aria-selected={active===c.id}>{c.displayName}</button>)}</div><div className="cards">{shown.map(p=><ProductCard key={p.id} product={p} quantity={cart[p.id]||0} onChange={change}/>)}</div></section>
 <ReviewsSection/><section id="about" className="about"><div><p className="eyebrow">Ешь!ка в Таганроге</p><h2>Быстрый заказ, чтобы забрать еду с собой</h2></div><dl><div><dt>Адрес</dt><dd>{business.shortAddress}</dd></div><div><dt>Средний чек</dt><dd>{business.averageCheck}</dd></div><div><dt>Режим работы</dt><dd>{business.schedule}</dd></div></dl></section>
 <section id="contacts" className="contacts"><div><p className="eyebrow">Контакты</p><h2>Ешь!ка</h2><p>{business.address}</p><a href={`tel:${business.phoneHref}`}>{business.phone}</a><a href={business.vk} target="_blank" rel="noopener noreferrer">vk.ru/ehska.taganrog ↗</a>{business.yandexEdaUrl&&<a className="yandex-link" href={business.yandexEdaUrl} target="_blank" rel="noopener noreferrer">Заказать через Яндекс Еду ↗</a>}</div><div className="map-placeholder" aria-label="Место для карты"><span>Здесь появится карта</span><small>Подключите лёгкую карту при публикации</small></div></section></main>
 <footer><span className="logo">Ешь<span>!</span>ка</span><span>{business.shortAddress}</span><a href={business.vk}>VK</a><span>{business.schedule}</span></footer>
 {count>0&&<button className="mobile-cart" onClick={()=>setDrawer(true)}>{count} {count===1?"позиция":"позиции"} · {money(total)} <b>Корзина →</b></button>}
 {drawer&&<div className="overlay" onMouseDown={()=>setDrawer(false)}><aside className="drawer" role="dialog" aria-modal="true" aria-label="Ваша корзина" onMouseDown={e=>e.stopPropagation()}><div className="drawer-head"><h2>Ваш заказ</h2><button onClick={()=>setDrawer(false)} aria-label="Закрыть корзину">×</button></div>{cartProducts.length?<><div className="cart-list">{cartProducts.map(p=><div className="cart-item" key={p.id}><Image src={p.image ?? fallback} width={64} height={64} alt=""/><div><b>{p.name}</b><small>{money(p.price)}</small></div><div className="stepper"><button onClick={()=>change(p.id,-1)} aria-label={`Уменьшить ${p.name}`}>−</button><span>{cart[p.id]}</span><button onClick={()=>change(p.id,1)} aria-label={`Увеличить ${p.name}`}>+</button></div></div>)}</div><div className="drawer-total"><span>Итого</span><b>{money(total)}</b></div><Link className="primary checkout" href="/checkout" onClick={()=>setDrawer(false)}>Оформить заказ</Link><button className="clear" onClick={()=>setCart({})}>Очистить корзину</button></>:<div className="empty"><h3>В корзине пока пусто</h3><p>Добавьте что-нибудь вкусное из меню</p><button className="primary" onClick={()=>{setDrawer(false);choose(categories[0].id)}}>Перейти к меню</button></div>}</aside></div>}</> }
function ProductCard({product,quantity,onChange}:{product:Product;quantity:number;onChange:(id:string,a:number)=>void}){return <article className="card"><div className="food-image"><Image src={product.image ?? "/images/demo-food-fallback.svg"} fill sizes="(max-width: 680px) 50vw, 25vw" alt={`Фотография блюда: ${product.name}`} loading="lazy"/></div><div className="card-body"><h3>{product.name}</h3>{product.weight&&<small>{product.weight}</small>}{product.description&&<p>{product.description}</p>}<div className="card-bottom"><b>{money(product.price)}</b>{quantity?<div className="stepper"><button onClick={()=>onChange(product.id,-1)} aria-label={`Уменьшить ${product.name}`}>−</button><span>{quantity}</span><button onClick={()=>onChange(product.id,1)} aria-label={`Увеличить ${product.name}`}>+</button></div>:<button className="add" onClick={()=>onChange(product.id,1)} disabled={!product.available}>{product.available?"+ Добавить":"Нет в наличии"}</button>}</div></div></article>}
