import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
const input = process.argv[2];
if (!input) { console.error("Usage: npm run import:menu -- ./menu-source.json"); process.exit(1); }
const raw = JSON.parse(await readFile(resolve(input), "utf8"));
if (!Array.isArray(raw.categories) || !Array.isArray(raw.products)) throw new Error("JSON должен содержать categories и products.");
const categories = raw.categories.map((c, index) => ({ id: String(c.id), name: String(c.name), sortOrder: Number(c.sortOrder ?? index + 1) }));
const products = raw.products.map(p => ({ id: String(p.id), externalId: p.externalId ? String(p.externalId) : undefined, categoryId: String(p.categoryId), name: String(p.name), description: p.description ? String(p.description) : undefined, price: Number(p.price), weight: p.weight ? String(p.weight) : undefined, image: p.image ? String(p.image) : "/images/demo-food-fallback.svg", available: p.available !== false, source: p.source === "yandex" ? "yandex" : "manual" }));
if (products.some(p => !p.id || !p.categoryId || !p.name || !Number.isFinite(p.price) || p.price < 0)) throw new Error("В меню есть некорректная позиция.");
await writeFile(resolve("data/menu.imported.ts"), `// Generated by scripts/import-menu.mjs. Review before publishing.\nexport const importedMenu = ${JSON.stringify({ categories, products }, null, 2)} as const;\n`);
console.log("Imported", products.length, "products into data/menu.imported.ts");
